# Generated by Django 2.2.4 on 2019-08-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0002_model_testform_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_testform',
            old_name='agency',
            new_name='LeftLWidthDec',
        ),
        migrations.RenameField(
            model_name='model_testform',
            old_name='email',
            new_name='LeftLWidthInc',
        ),
        migrations.RenameField(
            model_name='model_testform',
            old_name='juristiction',
            new_name='blockID',
        ),
        migrations.RenameField(
            model_name='model_testform',
            old_name='name',
            new_name='centerLWidthDec',
        ),
        migrations.RenameField(
            model_name='model_testform',
            old_name='page',
            new_name='centerLWidthInc',
        ),
        migrations.RenameField(
            model_name='model_testform',
            old_name='postitle',
            new_name='consistantBlock',
        ),
        migrations.AddField(
            model_name='model_testform',
            name='gutterWidthDec',
            field=models.CharField(default='asdf', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='gutterWidthInc',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='horAlignment',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='medianType',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='parkSpecialLane',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='rightLWidthDec',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='rightLWidthInc',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='rodwayType',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='shoulderTypeDec',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='shoulderTypeInc',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='shoulderWidthDec',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='shoulderWidthInc',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='speedLimit',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='state',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_testform',
            name='username',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
    ]
