# Generated by Django 2.2.4 on 2019-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0003_auto_20190823_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_testform',
            name='blockID',
            field=models.CharField(error_messages={'unique': 'This blockID already exists.'}, max_length=264, unique=True),
        ),
    ]
