# Generated by Django 2.2.4 on 2019-09-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0006_auto_20190904_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_testform',
            name='blockID',
            field=models.CharField(error_messages={'unique': 'This Block ID already exists.'}, max_length=264, unique=True),
        ),
    ]
