# Generated by Django 2.2.4 on 2019-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0021_auto_20191001_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_testform',
            name='LeftLWidthDec',
            field=models.BigIntegerField(max_length=264),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='LeftLWidthInc',
            field=models.BigIntegerField(max_length=264),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='blockID',
            field=models.BigIntegerField(error_messages={'unique': 'This Block ID already exists.'}, max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='centerLWidthDec',
            field=models.BigIntegerField(max_length=264),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='centerLWidthInc',
            field=models.BigIntegerField(max_length=264),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='gutterWidthDec',
            field=models.BigIntegerField(max_length=264),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='gutterWidthInc',
            field=models.BigIntegerField(max_length=264),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='rightLWidthDec',
            field=models.BigIntegerField(max_length=264),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='rightLWidthInc',
            field=models.BigIntegerField(max_length=264),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='shoulderWidthDec',
            field=models.BigIntegerField(max_length=264),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='shoulderWidthInc',
            field=models.BigIntegerField(max_length=264),
        ),
    ]
