# Generated by Django 2.2.4 on 2019-10-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0029_model_testform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_testform',
            name='user',
        ),
    ]
