# Generated by Django 2.2.4 on 2019-10-09 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testform', '0030_remove_model_testform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_testform',
            name='users',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
