# Generated by Django 2.2.4 on 2019-10-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0036_remove_model_testform_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_testform',
            name='speedLimit',
            field=models.CharField(max_length=264),
        ),
    ]
