# Generated by Django 2.2.4 on 2019-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0037_auto_20191009_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_testform',
            name='centerLWidthDec',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
