# Generated by Django 2.2.4 on 2019-10-15 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0042_auto_20191015_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_testform',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
