# Generated by Django 2.2.4 on 2019-10-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testform', '0043_auto_20191015_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_testform',
            name='username',
        ),
        migrations.AddField(
            model_name='model_testform',
            name='editBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userEdit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='model_testform',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userCreate', to=settings.AUTH_USER_MODEL),
        ),
    ]
