# Generated by Django 2.2.4 on 2019-10-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0045_auto_20191016_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_testform',
            name='author',
            field=models.ForeignKey(default='ADMIN', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
