# Generated by Django 2.2.4 on 2019-10-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0048_auto_20191016_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_testform',
            name='username',
            field=models.CharField(default='test', max_length=264),
            preserve_default=False,
        ),
    ]
