# Generated by Django 2.2.4 on 2019-10-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0050_auto_20191016_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_testform',
            name='username',
        ),
    ]
