# Generated by Django 2.2.4 on 2020-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='model_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectDesc', models.CharField(default='Project', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='model_utilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('project', models.CharField(max_length=264)),
                ('hours', models.FloatField()),
                ('week', models.CharField(max_length=264)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
